name: komaru_web
description: "komaru web Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # icons
  cupertino_icons: ^1.0.6
  # localization
  flutter_localization: ^0.2.0
  # shared_preferences
  shared_preferences: ^2.2.3
  # router
  katana_router: ^2.2.10
  # riverpod
  riverpod: ^2.5.1
  riverpod_generator: ^2.4.0
  riverpod_annotation: ^2.3.5
  # sound
  flutter_sound: ^9.4.6
  # collection
  collection: ^1.18.0
  # grid
  pluto_grid: ^7.0.2
  # info
  package_info_plus: ^7.0.0
  # dialog
  awesome_dialog: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # lints
  flutter_lints: ^3.0.0
  # build_runner
  build_runner: ^2.4.9
  # router
  katana_router_builder: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
  fonts:
    - family: Murecho
      fonts:
        - asset: assets/fonts/Murecho/static/Murecho-Thin.ttf
          weight: 100
        - asset: assets/fonts/Murecho/static/Murecho-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Murecho/static/Murecho-Light.ttf
          weight: 300
        - asset: assets/fonts/Murecho/static/Murecho-Regular.ttf
          weight: 400
        - asset: assets/fonts/Murecho/static/Murecho-Medium.ttf
          weight: 500
        - asset: assets/fonts/Murecho/static/Murecho-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Murecho/static/Murecho-Bold.ttf
          weight: 700
        - asset: assets/fonts/Murecho/static/Murecho-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Murecho/static/Murecho-Black.ttf
          weight: 900
